Repository kjs990114/SKKU.GG, pull requests merged in 2022-11, with the labels that each got.

#1 로그인 페이지 css 디자인
  public/css/font/FrutigerLTStd-Bold.woff
  public/css/font/pala.woff
  public/css/img/emblem.png
  public/css/style.css
  public/index.html
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#3 user 정보에 티어 추가
  public/index.html
  public/main.html
  public/mypage.html
  public/searching.html
  server.js
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#4 add css to main.html
  public/css/main.css
  public/main.html
  server.js
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#6 Dev/searching
  public/css/img/-.png
  public/css/img/Emblem_Bronze.png
  public/css/img/Emblem_Challenger.png
  public/css/img/Emblem_Diamond.png
  public/css/img/Emblem_Gold.png
  public/css/img/Emblem_Grandmaster.png
  public/css/img/Emblem_Iron.png
  public/css/img/Emblem_Master.png
  public/css/img/Emblem_Platinum.png
  public/css/img/Emblem_Silver.png
  public/css/img/Emblem_Unrank.png
  public/main.html
  public/searching.html
  server.js
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#8 로그인시 티어정보 잘못 가져오는 버그 수정
  public/index.html
Labels: :hammer_and_wrench: 새 기능 / 개선, :+1: 해결

#13 add css to search.html
  public/css/search.css
  public/searching.html
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요, :+1: 해결

#14 Ranking system 구현
  .DS_Store
  public/ranking.html
  server.js
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#16 select 로 학과선택하게 변경
  public/css/style.css
  public/index.html
  public/searching.html
  server.js
Labels: :hammer_and_wrench: 새 기능 / 개선, :+1: 해결

#17 Ranking CSS V1.1.0
  .DS_Store
  public/css/ranking.css
  public/ranking.html
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#18 Ranking system Update
  .DS_Store
  public/css/ranking.css
  public/js/ranking.js
  public/ranking.html
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#19 자잘한 기능 추가
  .vs/SKKU.GG/v17/.suo
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  public/main.html
  public/mypage.html
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#21 main.html변경
  public/css/main.css
  public/css/mypage.css
  public/js/main.js
  public/main.html
  public/mypage.html
  server.js
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요

#22 로그인 중복 체크 기능 추가
  public/index.html
  server.js
Labels: :hammer_and_wrench: 새 기능 / 개선, :eyes: 리뷰 필요
